// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDeLabWeb.Data;

namespace ProjetoDeLabWeb.Migrations
{
    [DbContext(typeof(ProjetoDeLabWebContext))]
    [Migration("20210125203600_addRestaurante")]
    partial class addRestaurante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoDeLabWeb.Models.Restaurante", b =>
                {
                    b.Property<int>("IdRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaDescanco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Domingo_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HorarioCriado")
                        .HasColumnType("bit");

                    b.Property<string>("HorarioFunc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NdePreferem")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuartaFeira_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<bool>("QuintaFeira_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<bool>("RestauranteAceite")
                        .HasColumnType("bit");

                    b.Property<bool>("Sabado_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<bool>("SegundaFeira_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<bool>("SextaFeira_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TercaFeira_PratoDoDia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("IdRestaurante");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("ProjetoDeLabWeb.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegistoConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("ProjetoDeLabWeb.Models.Restaurante", b =>
                {
                    b.HasOne("ProjetoDeLabWeb.Models.Utilizador", "UtilizadorDono")
                        .WithMany("Restaurantes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
